- title: "Network Namespace 1 (ns1) Status"
  checks:
    - name: "ns1"
      command: "ip addr show | grep mpq | grep -q 'state UP'"
    - name: "ns2"
      command: "grep -q true test/file1.txt"
    - name: "ns3"
      command: "grep -q true test/file3.txt"
    - name: "ns4"
      command: "grep -q true test/file4.txt"