# Global settings
poll_interval: 0.8  # Default polling interval in seconds

# Check sections
- title: "Network Namespace 1 (ns1) Status"
  checks:
    - name: "ns1"
      command: "ip addr show | grep mpq | grep -q 'state UP'"
    - name: "ns2"
      command: "grep -q true test/file1.txt"
      poll_interval: 1.5  # Override for this specific check
    - name: "ns3"
      command: "grep -q true test/file3.txt"
    - name: "ns4"
      command: "grep -q true test/file4.txt"
      poll_interval: 2.0  # Slower polling for this check